[project]
name = "4-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "laser-learning-environment>=2.6.1",
    "multi-agent-rlenv>=3.6.3",
    "opencv-python>=4.11.0.86",
    "seaborn>=0.13.2",
]
